version: "3"

services:
  db_saqibrazzaq_com:
    image: mysql:5.7
    volumes:
      - db_saqibrazzaq_com:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: saqibrazzaq
      MYSQL_PASSWORD: password
    container_name: db_saqibrazzaq_com
    networks:
      - net_saqibrazzaq_com
    
  wp_saqibrazzaq_com:
    depends_on:
      - db_saqibrazzaq_com
    image: wordpress:latest
    expose:
      - 80
    restart: always
    environment:
      VIRTUAL_HOST: saqibrazzaq.com
      LETSENCRYPT_HOST: saqibrazzaq.com
      LETSENCRYPT_EMAIL: "saqibrazzaq@gmail.com"
      WORDPRESS_DB_HOST: db_saqibrazzaq_com:3306
      WORDPRESS_DB_USER: saqibrazzaq
      WORDPRESS_DB_PASSWORD: password
    container_name: wp_saqibrazzaq_com
    networks:
      - nginx-proxy
      - net_saqibrazzaq_com
    
  db_blog_saqibrazzaq_com:
    image: mysql:5.7
    volumes:
      - db_blog_saqibrazzaq_com:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: saqibrazzaq
      MYSQL_PASSWORD: password
    container_name: db_blog_saqibrazzaq_com
    networks:
      - net_blog_saqibrazzaq_com
    
  wp_blog_saqibrazzaq_com:
    depends_on:
      - db_blog_saqibrazzaq_com
    image: wordpress:latest
    expose:
      - 80
    restart: always
    environment:
      VIRTUAL_HOST: blog.saqibrazzaq.com
      LETSENCRYPT_HOST: blog.saqibrazzaq.com
      LETSENCRYPT_EMAIL: "saqibrazzaq@gmail.com"
      WORDPRESS_DB_HOST: db_blog_saqibrazzaq_com:3306
      WORDPRESS_DB_USER: saqibrazzaq
      WORDPRESS_DB_PASSWORD: password
    container_name: wp_blog_saqibrazzaq_com
    networks:
      - nginx-proxy
      - net_blog_saqibrazzaq_com
    
volumes:
  db_saqibrazzaq_com:
  db_blog_saqibrazzaq_com:

networks:
  nginx-proxy:
    external: true
  net_saqibrazzaq_com:
    internal: true
  net_blog_saqibrazzaq_com:
    internal: true