version: "3"

services:
  xptrackercs_db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: xptrackercs_db
    volumes:
      - xptrackercs_db:/var/opt/mssql/data
    environment:
      SA_PASSWORD: "Saqib123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433"
    restart: always
    networks:
      - xptrackercs_db

  xptrackercs_api:
    image: saqibrazzaq/xptrackercs_api
    container_name: xptrackercs_api
    environment:
      VIRTUAL_HOST: xptrackercs-api.saqibrazzaq.com
      LETSENCRYPT_HOST: xptrackercs-api.saqibrazzaq.com
      LETSENCRYPT_EMAIL: "saqibrazzaq@gmail.com"
    expose:
      - 80
    depends_on:
      - xptrackercs_db
    restart: always
    networks:
      - nginx-proxy
      - xptrackercs_db

  xptrackercs_web:
    image: saqibrazzaq/xptrackercs_web
    container_name: xptrackercs_web
    environment:
      VIRTUAL_HOST: xptrackercs-web.saqibrazzaq.com
      LETSENCRYPT_HOST: xptrackercs-web.saqibrazzaq.com
      LETSENCRYPT_EMAIL: "saqibrazzaq@gmail.com"
      CHOKIDAR_USEPOLLING: true
    expose:
      - 80
    stdin_open: true
    tty: true
    depends_on:
      - xptrackercs_api
    restart: always
    networks:
      - nginx-proxy

volumes:
  xptrackercs_db:

networks:
  nginx-proxy:
    external: true
  xptrackercs_db:
    internal: true