version: "3"

services:
  xptrackercs_db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: xptrackercs_db
    volumes:
      - xptrackercs_db:/var/opt/mssql/data
    environment:
      SA_PASSWORD: "Saqib123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1437:1433"
    restart: always

  xptrackercs_api:
    image: saqibrazzaq/xptrackercs_api
    container_name: xptrackercs_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "50530:80"
      - "50531:443"
    depends_on:
      - xptrackercs_db
    restart: always

  xptrackercs_web:
    image: saqibrazzaq/xptrackercs_web
    container_name: xptrackercs_web
    ports:
      - '80:3000'
    stdin_open: true
    tty: true
    depends_on:
      - xptrackercs_api
    restart: always

volumes:
  xptrackercs_db: