version: "3"

services:
  db_xptrackerscs:
    image: mcr.microsoft.com/mssql/server:2017-latest
    volumes:
      - db_data:/var/opt/mssql/data
    environment:
      SA_PASSWORD: "Saqib123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1437:1433"

volumes:
  db_xptrackerscs: