version: "3"

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    container_name: keycloack_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - postgres.env
    networks:
      - nginx-proxy
      - keycloack_db
    restart: always
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloack
    environment:
      VIRTUAL_HOST: keycloack.efcorebeginner.com
      LETSENCRYPT_HOST: keycloack.efcorebeginner.com
      LETSENCRYPT_EMAIL: "saqibrazzaq@gmail.com"
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      KC_HOSTNAME: keycloack.efcorebeginner.com
      PROXY_ADDRESS_FORWARDING: true
      REDIRECT_SOCKET: "proxy-https"
      KEYCLOAK_FRONTEND_URL: https://keycloak.efcorebeginner.com/auth
      KC_HTTPS_PORT: 443
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    expose:
      - 443
    env_file:
      - keycloack.env
    networks:
      - keycloack_db
    restart: always
    ports:
        - "443"
    depends_on:
      - postgres

networks:
  nginx-proxy:
    external: true
  keycloack_db:
    internal: true