version: '3.7'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      VIRTUAL_HOST: keycloak.efcorebeginner.com
      LETSENCRYPT_HOST: keycloak.efcorebeginner.com
      LETSENCRYPT_EMAIL: "saqibrazzaq@gmail.com"
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_HOSTNAME: keycloak.efcorebeginner.com
      # KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      PROXY_ADDRESS_FORWARDING: true
      # KC_HTTPS_CERTIFICATE_FILE: certs:/etc/nginx/certs/keycloak.efcorebeginner.com.crt
      # KC_HTTPS_CERTIFICATE_KEY_FILE: certs:/etc/nginx/certs/keycloak.efcorebeginner.com.key
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    # ports:
    #   - 443:443
    env_file:
      - keycloack.env
    networks:
      - nginx-proxy
    command: 
      - start-dev #--optimized
    # restart: always
    volumes:
      - certs:/etc/nginx/certs:ro

networks:
  nginx-proxy:
    external: true
  keycloack_db:
    internal: true

volumes:
  certs: