version: '3.7'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      VIRTUAL_HOST: keycloak.efcorebeginner.com
      LETSENCRYPT_HOST: keycloak.efcorebeginner.com
      LETSENCRYPT_EMAIL: saqibrazzaq@gmail.com
      VIRTUAL_PORT: "8080"
      KC_HOSTNAME: keycloak.efcorebeginner.com
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      HTTPS_METHOD: redirect
      KC_PROXY: edge
      KC_HTTPS_PORT: 443
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    # ports:
    #   - 443:443
    env_file:
      - keycloack.env
    networks:
      - nginx-proxy
    command: 
      - start #--optimized
    restart: unless-stopped
    
networks:
  nginx-proxy:
    external: true
