version: "3"

services:
  area_db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: area_db
    volumes:
      - area_db:/var/opt/mssql/data
    environment:
      SA_PASSWORD: "password"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433"
    restart: always
    networks:
      - area_db

  area_api:
    image: saqibrazzaq/area_api
    container_name: area_api
    environment:
      VIRTUAL_HOST: area-api.saqibrazzaq.com
      LETSENCRYPT_HOST: area-api.saqibrazzaq.com
      LETSENCRYPT_EMAIL: "saqibrazzaq@gmail.com"
    expose:
      - 80
    depends_on:
      - area_db
    restart: always
    networks:
      - nginx-proxy
      - area_db

  area_web:
    image: saqibrazzaq/area_web
    container_name: area_web
    environment:
      VIRTUAL_HOST: area-web.saqibrazzaq.com
      LETSENCRYPT_HOST: area-web.saqibrazzaq.com
      LETSENCRYPT_EMAIL: "saqibrazzaq@gmail.com"
      CHOKIDAR_USEPOLLING: true
    expose:
      - 80
    #stdin_open: true
    #tty: true
    depends_on:
      - area_api
    restart: always
    networks:
      - nginx-proxy
    volumes:
      - /app/node_modules
      - ./area_web:/app

volumes:
  area_db:

networks:
  nginx-proxy:
    external: true
  area_db:
    internal: true