version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - postgres.env
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - nginx-proxy
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    PGADMIN_ENABLE_TLS: true
    PGADMIN_LISTEN_PORT: 4443
    ports:
      - "480:80"
      - "4443:443"
    env_file:
      - pgadmin4.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - nginx-proxy

volumes:
  local_pgdata:
  pgadmin-data:

networks:
  nginx-proxy:
    external: true